name: CI/CD Deployment 
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sinatra-cats:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/sinatra-cats:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sinatra-cats:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sinatra-cats:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sinatra-cats:latest

      - name: Deploy to K8s
        run: |
          kubectl apply -f deploy/
